### ISSUE TITLE
TermsQuery defines optional property as required

### ISSUE THREAD

**Issue by pschulzk** [SiNEXiST/elastic-types#2] opened 2020-02-19 09:32 UTC
## Description
Type [`TermsQuery`](https://github.com/SiNEXiST/elastic-types/blob/master/src/queries/terms.ts) defines `terms` to contain `value` property as non-optional which is not necessary according to the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#terms-query-ex-request).

## Expected behavior
`const foo: TermsQuery = { terms: { [property]: [ 0, 1, 2 ] } }; // no error`

## Actual behavior
`const foo: TermsQuery = { terms: { [property]: [ 0, 1, 2 ] } }; // type error`
`const foo: TermsQuery = { terms: { [property]: [ 0, 1, 2 ], value: null } }; // forced to set "value"`

**Comment by deckdom** [comment] 2020-03-04 21:15
Should be resolved with v0.1.3.
Feel free to reopen if the issue isn't resolved yet.

**Closed as completed by deckdom** 2020-03-04 21:15 UTC
